baseurl: "https://benjamin-williams.github.io"
publishDir: "docs"
languageCode: "en-us"
title: "Ben Williams"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"


menu:
  main:
    - name: home
      url: ""
      weight: 1
    - name: cv
      url: "cv.pdf"
      weight: 2

params:
  description: "blah blah"
  footer: "&copy; Ben Williams, 2022 | created with [xmin](https://xmin.yihui.org/) on [Hugo](https://gohugo.io/)" 
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
